default_stages: [pre-commit]

repos:
  # External hook: strip trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]

  # Local hooks
  - repo: local
    hooks:
      - id: unit-tests
        name: Run add() unit tests
        entry: task test:local
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
